=== CU-DBMI/rtx-kg2-gateway/src/notebooks/data/kg2c_lite_2.8.4.sample.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "https://github.com/CU-DBMI/rtx-kg2-gateway/src/notebooks/data/kg2c_lite_2.8.4.schema.json",
  "description": "Inferred JSON Schema from subset of RTX-KG2 JSON data for documenting data provenance.",
  "type": "object",
  "properties": {
    "nodes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "all_categories": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "category": {
            "type": "string"
          }
        },
        "required": [
          "all_categories",
          "category",
          "id",
          "name"
        ]
      }
    },
    "edges": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "qualified_object_aspect": {
            "type": "string"
          },
          "predicate": {
            "type": "string"
          },
          "domain_range_exclusion": {
            "type": "string"
          },
          "object": {
            "type": "string"
          },
          "qualified_object_direction": {
            "type": "string"
          },
          "id": {
            "type": "integer"
          },
          "primary_knowledge_source": {
            "type": "string"
          },
          "subject": {
            "type": "string"
          },
          "qualified_predicate": {
            "type": "string"
          }
        },
        "required": [
          "domain_range_exclusion",
          "id",
          "object",
          "predicate",
          "primary_knowledge_source",
          "qualified_object_aspect",
          "qualified_object_direction",
          "qualified_predicate",
          "subject"
        ]
      }
    },
    "kg2_version": {
      "type": "string"
    },
    "biolink_version": {
      "type": "string"
    }
  },
  "required": [
    "biolink_version",
    "edges",
    "kg2_version",
    "nodes"
  ]
}

=== CU-DBMI/rtx-kg2-gateway/src/notebooks/data/kg2c_lite_2.8.4.sample.json
{
  "nodes": [
    {
      "id": "biolink_download_source:biolink-model.owl.ttl",
      "name": "Biolink meta-model version downloaded:2023-07-20 21:19:46 GMT",
      "all_categories": [
        "biolink:RetrievalSource"
      ],
      "category": "biolink:RetrievalSource"
    },
    {
      "id": "biolink:overlaps",
      "name": "overlaps",
      "all_categories": [
        "biolink:InformationContentEntity"
      ],
      "category": "biolink:InformationContentEntity"
    }
  ],
  "edges": [
    {
      "qualified_object_aspect": "",
      "predicate": "biolink:subclass_of",
      "domain_range_exclusion": "False",
      "object": "biolink:overlaps",
      "qualified_object_direction": "",
      "id": 1,
      "primary_knowledge_source": "infores:biolink-ontology",
      "subject": "FMA:has_part",
      "qualified_predicate": ""
    },
    {
      "qualified_object_aspect": "",
      "predicate": "biolink:subclass_of",
      "domain_range_exclusion": "False",
      "object": "biolink:overlaps",
      "qualified_object_direction": "",
      "id": 2,
      "primary_knowledge_source": "infores:biolink-ontology",
      "subject": "UMLS:C1292711",
      "qualified_predicate": ""
    }
  ],
  "kg2_version": "2.8.4",
  "biolink_version": "3.1.2"
}
